language: groovy
#Jenkins LTS core uses Groovy 2.4.8 as of 2017-09-17
env:
  # Jenkins 1.x uses Groovy 1.8.9
  - GROOVY_VERSION="1.8.9"
  # Jenkins 2.0 onward uses Groovy 2.4.6
  - GROOVY_VERSION="2.4.6"
  # Jenkins 2.47 onward uses Groovy 2.4.8
  - GROOVY_VERSION="2.4.8"
  # Jenkins 2.61 onward uses Groovy 2.4.11
  - GROOVY_VERSION="2.4.11"
  # Latest Groovy 2.4.x stable
  - GROOVY_VERSION="2.4.12"
  # Latest Groovy 2.5.x prerelease (next Groovy release)
  - GROOVY_VERSION="2.5.0-beta-1"
#gradle doesn't have a retry for assembling dependencies so here's one in bash
install: ./assemble.sh
script: ./gradlew cobertura
after_success:
  - ./coveralls.sh
matrix:
  allow_failures:
    - env: GROOVY_VERSION="1.8.9"
    - env: GROOVY_VERSION="2.4.6"
    - env: GROOVY_VERSION="2.4.8"
    - env: GROOVY_VERSION="2.4.12"
    - env: GROOVY_VERSION="2.5.0-beta-1"
branches:
  only:
    - master
    - jervis_simple
#https://docs.travis-ci.com/user/languages/groovy#caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jenkins:
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/*.xml
    cobertura: build/reports/cobertura/coverage.xml
