language: groovy
#Jenkins LTS core uses Groovy 2.4.8 as of 2017-09-17
env:
  - GROOVY_VERSION="1.8.9"
  - GROOVY_VERSION="2.0.8"
  - GROOVY_VERSION="2.1.9"
  - GROOVY_VERSION="2.2.2"
  - GROOVY_VERSION="2.3.11"
  - GROOVY_VERSION="2.4.8"
  - GROOVY_VERSION="2.4.12"
#gradle doesn't have a retry for assembling dependencies so here's one in bash
install: ./assemble.sh
script: ./gradlew cobertura
after_success:
  - ./coveralls.sh
matrix:
  allow_failures:
    - env: GROOVY_VERSION="1.8.9"
    - env: GROOVY_VERSION="2.0.8"
    - env: GROOVY_VERSION="2.1.9"
    - env: GROOVY_VERSION="2.2.2"
    - env: GROOVY_VERSION="2.3.11"
    - env: GROOVY_VERSION="2.4.12"
branches:
  only:
    - master
    - jervis_simple
#https://docs.travis-ci.com/user/languages/groovy#caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jenkins:
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/*.xml
    cobertura: build/reports/cobertura/coverage.xml
